"""remove unique constraint on gym name

Revision ID: 3d5c1339ff88
Revises: ed0b24cdec23
Create Date: 2026-03-10 16:23:44.108982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5c1339ff88'
down_revision: Union[str, Sequence[str], None] = 'ed0b24cdec23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gyms_name'), table_name='gyms')
    op.create_index(op.f('ix_gyms_name'), 'gyms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gyms_name'), table_name='gyms')
    op.create_index(op.f('ix_gyms_name'), 'gyms', ['name'], unique=True)
    # ### end Alembic commands ###
