"""add hashed password

Revision ID: c0dcae4c6ec9
Revises: 3d5c1339ff88
Create Date: 2026-03-13 00:13:41.259056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dcae4c6ec9'
down_revision: Union[str, Sequence[str], None] = '3d5c1339ff88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'hashed_password')
    # ### end Alembic commands ###
