"""add indexes to fk columns

Revision ID: f598a6d17dd0
Revises: c0dcae4c6ec9
Create Date: 2026-03-19 01:32:08.299796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f598a6d17dd0'
down_revision: Union[str, Sequence[str], None] = 'c0dcae4c6ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_members_gym_id'), 'members', ['gym_id'], unique=False)
    op.create_index(op.f('ix_progress_member_id'), 'progress', ['member_id'], unique=False)
    op.create_index(op.f('ix_progress_workout_id'), 'progress', ['workout_id'], unique=False)
    op.create_index(op.f('ix_progress_workout_session_id'), 'progress', ['workout_session_id'], unique=False)
    op.create_index(op.f('ix_staff_gym_id'), 'staff', ['gym_id'], unique=False)
    op.create_index(op.f('ix_workout_body_part_id'), 'workout', ['body_part_id'], unique=False)
    op.create_index(op.f('ix_workout_session_gym_id'), 'workout_session', ['gym_id'], unique=False)
    op.create_index(op.f('ix_workout_session_staff_id'), 'workout_session', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_session_staff_id'), table_name='workout_session')
    op.drop_index(op.f('ix_workout_session_gym_id'), table_name='workout_session')
    op.drop_index(op.f('ix_workout_body_part_id'), table_name='workout')
    op.drop_index(op.f('ix_staff_gym_id'), table_name='staff')
    op.drop_index(op.f('ix_progress_workout_session_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_workout_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_member_id'), table_name='progress')
    op.drop_index(op.f('ix_members_gym_id'), table_name='members')
    # ### end Alembic commands ###
