"""
member.py — Pydantic Schemas for Member

Members are tenant-scoped: every member belongs to a gym via gym_id.
gym_id is required on create and returned on response, but not updatable.
"""

from pydantic import BaseModel, EmailStr
from datetime import datetime


class MemberCreate(BaseModel):
    """Fields the client must send when registering a new member.

    gym_id links the member to an existing gym (tenant).
    email is validated as a proper email format by Pydantic.
    """
    gym_id: int
    name: str
    email: EmailStr
    phone: str


class MemberUpdate(BaseModel):
    """Fields the client may send when updating a member.

    All fields are optional — only send what needs to change.
    gym_id is excluded: members cannot be reassigned to a different gym.
    """
    name: str | None = None
    email: EmailStr | None = None
    phone: str | None = None


class MemberResponse(BaseModel):
    """Full member data returned by the API after any successful operation.

    Includes all fields: id, gym_id, and timestamps generated by the database.
    model_config allows Pydantic to read directly from SQLAlchemy model instances.
    """
    id: int
    gym_id: int
    name: str
    email: EmailStr
    phone: str
    created_at: datetime
    updated_at: datetime
    model_config = {"from_attributes": True}
    # "finish"
