"""
staff.py — Pydantic Schemas for Staff

Staff are tenant-scoped: every staff member belongs to a gym via gym_id.
Role is restricted to RoleEnum values (manager, trainer) — validated at API level.
"""

from pydantic import BaseModel, EmailStr
from datetime import datetime
from app.models.staff import RoleEnum


class StaffCreate(BaseModel):
    """Fields the client must send when registering a new staff member.

    gym_id links the staff to an existing gym (tenant).
    role must be either 'manager' or 'trainer' — enforced by RoleEnum.
    """
    role: RoleEnum
    name: str
    email: EmailStr
    phone: str
    gym_id: int


class StaffUpdate(BaseModel):
    """Fields the client may send when updating a staff member.

    All fields are optional — only send what needs to change.
    gym_id is excluded: staff cannot be reassigned to a different gym.
    """
    role: RoleEnum | None = None
    name: str | None = None
    email: EmailStr | None = None
    phone: str | None = None


class StaffResponse(BaseModel):
    """Full staff data returned by the API after any successful operation.

    Includes all fields: id, gym_id, role, and timestamps generated by the database.
    model_config allows Pydantic to read directly from SQLAlchemy model instances.
    """
    id: int
    role: RoleEnum
    gym_id: int
    name: str
    email: EmailStr
    phone: str
    created_at: datetime
    updated_at: datetime
    model_config = {"from_attributes": True}
