"""
workout.py — Pydantic Schemas for Workout and BodyPart

Two models live here because Workout depends on BodyPart via body_part_id.
Workouts are NOT gym-scoped — they are shared across all gyms.
"""

from pydantic import BaseModel
from datetime import datetime


class WorkoutCreate(BaseModel):
    """Fields the client must send when creating a new workout.

    body_part_id is required to link the workout to an existing body part (e.g. Chest, Legs).
    """
    name: str
    body_part_id: int


class WorkoutUpdate(BaseModel):
    """Fields the client may send when updating a workout.

    All fields are optional — only send what needs to change.
    """
    name: str | None = None
    body_part_id: int | None = None


class WorkoutResponse(BaseModel):
    """Full workout data returned by the API after any successful operation.

    Includes id, body_part_id, and timestamps generated by the database.
    model_config allows Pydantic to read directly from SQLAlchemy model instances.
    """
    id: int
    name: str
    body_part_id: int
    created_at: datetime
    updated_at: datetime
    model_config = {"from_attributes": True}


# BodyPart is the parent of Workout (one BodyPart → many Workouts)

class BodyPartCreate(BaseModel):
    """Fields the client must send when creating a new body part (e.g. 'Chest', 'Legs')."""
    name: str


class BodyPartUpdate(BaseModel):
    """Fields the client may send when updating a body part. All optional."""
    name: str | None = None


class BodyPartResponse(BaseModel):
    """Full body part data returned by the API after any successful operation."""
    name: str
    id: int
    created_at: datetime
    updated_at: datetime
    model_config = {"from_attributes": True}
